# Generated by Django 4.1.5 on 2023-01-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_comment_options_comment_ad_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ad',
            field=models.ManyToManyField(to='ads.ad'),
        ),
    ]
