# Generated by Django 4.1.5 on 2023-01-23 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_remove_comment_ad_comment_ad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
